### ISSUE TITLE
Deploy errors

### ISSUE THREAD

**Issue by tbillington** [XAMPPRocky/mean-bean-ci-template#1]
Firstly wanted to say thank you for creating this project, I think it's super helpful for me trying to get set up !

I added the deploy script, and the `ci` folder to my project. Installing cross worked fine, but neither mac nor linux worked, with both erroring on permission denied

```
Run ci/set_rust_version.bash stable x86_64-apple-darwin
  ci/set_rust_version.bash stable x86_64-apple-darwin
  shell: /bin/bash -e {0}
  env:
    BIN: kondo
/Users/runner/runners/2.165.2/work/_temp/cfa3d4a1-1403-4197-964d-28071e47ecbe.sh: line 1: ci/set_rust_version.bash: Permission denied
##[error]Process completed with exit code 1.
```

Windows didn't error and looked like it succeeded but no windows build showed in the artifacts list so I don't know if that actually succeeded?

You can see the action runs here: https://github.com/tbillington/kondo/actions/runs/42964328.

Happy to provide more info if I can.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That is odd. Could I ask if you could delete the `v0.2` release on GitHub and then re-run the deploy action? That issue seems odd when the first line of the script is `#!/usr/bin/env bash`. I want to know if can it be reproduced.

**Comment by tbillington** [comment]
I had the same thought :) I ran it 3 times, you can see the first 2 here. I removed most of the targets for the 3rd one because it seemed wasteful but otherwise nothing else was changed.

https://github.com/tbillington/kondo/actions?query=workflow%3A%22Kondo+Deploy%22

Let me know if you'd still like me to re-push the tag!

**Comment by tbillington** [comment]
Hmm, the pull request you made didn't seem to change anything https://github.com/tbillington/kondo/actions/runs/43268762.

Could it be because I copied the ci scripts from a local clone of your project into mine in windows, and file permissions weren't respected? Wild guess

**Comment by XAMPPRocky** [comment]
@tbillington It could be, I do not have a Windows machine (I'm on macOS) so I don't have a way to check that.

**Comment by tbillington** [comment]
Ok I did the copy on a mac machine and this is the git diff, suspicious. Going to try a re-release again.

```
➜  kondo git:(master) ✗ git diff
diff --git a/ci/build.bash b/ci/build.bash
old mode 100644
new mode 100755
diff --git a/ci/set_rust_version.bash b/ci/set_rust_version.bash
old mode 100644
new mode 100755
diff --git a/ci/test.bash b/ci/test.bash
old mode 100644
new mode 100755
```

**Comment by tbillington** [comment]
Heyyy, all looks good now :) https://github.com/tbillington/kondo/actions/runs/43672859

I guess users of this should be careful to preserve the permissions on the ci files, does that sound about right?

**Comment by XAMPPRocky** [comment]
@tbillington Yep, I'll keep that in mind, I'm glad it all works now!
